FROM php:8.2-apache-bullseye as php

RUN apt-get update && \
    apt-get install -y libcurl4-openssl-dev pkg-config libssl-dev

RUN docker-php-ext-install mysqli pdo pdo_mysql && \
    docker-php-ext-configure curl --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install curl

RUN apt-get update && \
    apt-get install -y libpng-dev libwebp-dev libjpeg-dev libfreetype6-dev && \
    docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && \
    docker-php-ext-install gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN a2enmod rewrite
RUN a2enmod headers

COPY php.ini /usr/local/etc/php/

RUN sed -i 's/ErrorLog .*/ErrorLog \/var\/log\/apache2\/error.log/' /etc/apache2/sites-available/000-default.conf

RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip

RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

COPY ./www /var/www/html
WORKDIR /var/www/html
RUN ls -la

RUN rm -rf DOCKERFILE
RUN rm -rf .gitignore
RUN rm -rf .git
RUN rm -rf .gitignore.bak

RUN service apache2 restart

CMD ["apache2-foreground"]
